### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [huynguyencong/EzPopup#1]
Hi @huynguyencong  I am a graphic designer and i want to contribute by designing a logo for your project as a gift for free. I noticed that the project does not have a logo yet and i thought of helping out. If you will permit me i will start designing immediately and show you here. Thanks and best regards! 

- Tobaloidee

**Comment by huynguyencong** [comment]
Thank you, but this open source is not big, not many people know it, so I think it doesn't need a logo. Thank you for your kindness.

**Comment by Tobaloidee** [comment]
You're welcome, Thanks fpr the feedback..Best regards again!
