### ISSUE TITLE
Initial value not assigned when popupVC presents 

### ISSUE THREAD

**Issue by arishanapalli** [huynguyencong/EzPopup#13]
//CustomAlertViewController

```
    static func instantiate() -> CustomAlertViewController? {
        return UIStoryboard(name: "Main",bundle: nil).instantiateViewController(withIdentifier:
            "\(CustomAlertViewController.self)") as? CustomAlertViewController
    }

    func setAlertValues(alertTitle:String, alertMessage: String, isEnableCancel:Bool){
        self.lbl_AlertTitle?.text = alertTitle
        self.lbl_AlertMessage?.text = alertMessage
        self.btn_Cancel?.isHidden = isEnableCancel
    }
```

// DashboardViewController
 ```
   func shopPopUp(){
       customAlertViewController?.setAlertValues(alertTitle: "Alert Title", alertMessage: "Message box", isEnableCancel: true)
        let popupVC = PopupViewController(contentController: customAlertViewController!, position: .bottom(iPadToPhoneCustomSize(acutalSize: self.view.bounds.height/2 - 100)), popupWidth: self.view.bounds.width - iPadToPhoneCustomSize(acutalSize: 40), popupHeight: iPadToPhoneCustomSize(acutalSize: 200))
        popupVC.cornerRadius = iPadToPhoneCustomSize(acutalSize: 20)
        present(popupVC, animated: true, completion: nil)

    }
```

Above is my code which i am calling on click action.
First time click its shows the default values associated with design.

When click again then its start working with assigned value        customAlertViewController?.setAlertValues(alertTitle: "Alert Title", alertMessage: "Message box", isEnableCancel: true)

Where did went wrong do not understand please let me know!

**Comment by huynguyencong** [comment]
When you just create the UIViewController, views have not been inititalized. You should call viewController.view to initialize them. Another option is you should store those values to view controller properties, then assign those values to views in viewDidLoad of your view controller. It is not error of PopupViewController
