### ISSUE TITLE
How to position a popup correctly below the bottom edge of a UILabel ? 

### ISSUE THREAD

**Issue by Panchal-Harsh-98** [huynguyencong/EzPopup#14]
![Simulator Screen Shot - iPhone 11 - 2019-12-12 at 15 45 00](https://user-images.githubusercontent.com/43374041/70703617-7e9d6c00-1cf6-11ea-9db3-50240b83bc6b.png)

![my_requirement](https://user-images.githubusercontent.com/43374041/70704321-c5d82c80-1cf7-11ea-8bb8-745f2f679cfe.jpg)

Hi ,
I am trying to open a custom popup that is positioned exactly below a label's bottom edge. I was able to acheive the width and height according to my requirement , I also tried to play with the coordinate system but was not able to do so.

**Comment by huynguyencong** [comment]
I am adding a case of Position, that help you to show a pop up below a view. The code look like below:

```
 let popupVC = PopupViewController(
            contentController: pickerVC,
            position: .offsetFromView(CGPoint(x: 0, y: bottomButton.frame.height + 3), bottomButton),
            popupWidth: 100,
            popupHeight: 200
        )
```

Please update the pod in the next day.
