### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by cbartellds** [huynguyencong/EzPopup#2]
When I try to install using Cocoa Pods, I am getting the error:

[!] Unable to find a specification for `EzPopup`

My Podfile looks like this:

`// Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'EcardCategoryPlay' do
  // Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  // Pods for EcardCategoryPlay
pod 'SquareMosaicLayout', '4.1.1'
pod 'EzPopup'

  target 'EcardCategoryPlayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end`

**Comment by yeeket** [comment]
same here

**Comment by huynguyencong** [comment]
Please try run command `pod repo update` in command line
