### ISSUE TITLE
Popup VC not displaying properly

### ISSUE THREAD

**Issue by TriDivide** [huynguyencong/EzPopup#6]
Hi, I am trying to use you library and have followed the example project as close as I can but for some reason, the view controller that I am trying to display as a popup is not showing, the screen darkens but nothing else happens, do you have any insights for this?

**Comment by chap19150** [comment]
I'm seeing the same

**Comment by huynguyencong** [comment]
Have you inited popup with the popupWidth and popupHeight params? It can adjust popup size automatically if you config constraints to do that.

**Comment by jerryOkafor** [comment]
I am having the same issue, any solution yet?

**Comment by huynguyencong** [comment]
Do remember to set  `popupWidth` and `popupHeight` params and call present to present popup view.
