### ISSUE TITLE
Navigation handling ?

### ISSUE THREAD

**Issue by christopheblin** [huynguyencong/EzPopup#7]
If the inner view calls navigationController.pushViewController(controller, animated: true), it completely messes up the UI (popup stay above the new controller)

What is the proper way to keep navigation in the inner view ?

At the moment, we are dismissing the popup at the same time we use pushViewController but the problem is that when we use back the popup is not shown. Any idea ?

**Comment by huynguyencong** [comment]
The popup act like UIAlertController, so it is always showed on above other controllers. If you would like to push a view controller from the inner view controller (which present popup VC), you have to dismiss popup before. So you did the right thing. If you want the popup still there when backed, you need to present it again.

Thank you!
