### ISSUE TITLE
Popup not showing up correctly

### ISSUE THREAD

**Issue by AliVillegas** [huynguyencong/EzPopup#9]
I initiated the popup as in the example. The screen dims and the popup appears to be there but cannot be seen, I can even do the canTapOutsideToDismiss and it dismisses this 'invisible' popup. Any ideas on how to fix this ?

**Comment by jerryOkafor** [comment]
I am having similar issues, any solution yet?

**Comment by huynguyencong** [comment]
Please set the popupWidth and popupHeight when init pop up
